# Generated by Django 4.1 on 2022-11-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_mysecretmodel_delete_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield', models.CharField(max_length=10)),
                ('binaryfield', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='MySecretModel',
        ),
    ]
