# Generated by Django 4.1 on 2022-11-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_foobar_delete_mysecretmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foobar',
        ),
    ]
