# Generated by Django 4.1 on 2022-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0009_alter_user_database_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_database',
            name='group',
            field=models.CharField(blank=True, default='not_org_dwh', max_length=200),
        ),
    ]
